apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: esports-nexus
data:
  SPRING_PROFILES_ACTIVE: "production"
  SERVER_PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: esports-nexus
type: Opaque
data:
  # Base64 encoded values - replace with your own
  jwt-secret: ZXNwb3J0c05leHVzU2VjcmV0S2V5MjAyNFZlcnlMb25nQW5kU2VjdXJlS2V5
  google-client-id: eW91ci1nb29nbGUtY2xpZW50LWlk
  google-client-secret: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==
  discord-client-id: eW91ci1kaXNjb3JkLWNsaWVudC1pZA==
  discord-client-secret: eW91ci1kaXNjb3JkLWNsaWVudC1zZWNyZXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: esports-nexus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: esportsnexus/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://admin:your-secure-password@mongodb:27017/esports_nexus?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: google-client-secret
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: discord-client-id
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: discord-client-secret
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: esports-nexus
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080